export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const LOGIN_TO_ACCOUNT = "LOGIN_TO_ACCOUNT";
export const ERROR_CREATE_ACCOUNT = "ERROR_CREATE_ACCOUNT";
export const ERROR_LOGIN_TO_ACCOUNT = "ERROR_LOGIN_TO_ACCOUNT";
export const LOGOUT = "LOGOUT";
export const GET_TOWN = "GET_TOWN";
export const UPGRADE_BUILDING = "UPGRADE_BUILDING";
